services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["streamlit", "run", "application/app.py",  "--server.port", "8080"]
  test:
    build: .
    volumes:
      - .:/app
    command: ["pytest", "tests/test.py"]
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["uvicorn", "--host", "0.0.0.0", "--port", "8080", "api.api:app"]

